import { Gift, Sponsor, RaffleResult, Participant } from './types';

// ATTELIA Logo - Header için
export const ATTELIA_LOGO = '/ATTELIA.png';

// Sol taraf sponsorları (8 adet)
export const LEFT_SPONSORS: Sponsor[] = [
  {
    id: 'l1',
    name: 'Anisa',
    tier: 'gold',
    logoUrl: '/Anisa.png'
  },
  {
    id: 'l2',
    name: 'Bora',
    tier: 'gold',
    logoUrl: '/Bora.png'
  },
  {
    id: 'l3',
    name: 'Camlog',
    tier: 'gold',
    logoUrl: '/Camlog.png'
  },
  {
    id: 'l4',
    name: 'DMK',
    tier: 'gold',
    logoUrl: '/DMK.jpeg'
  },
  {
    id: 'l5',
    name: 'EDTA',
    tier: 'gold',
    logoUrl: '/EDTA.png'
  },
  {
    id: 'l6',
    name: 'EJ',
    tier: 'gold',
    logoUrl: '/EJ.png'
  },
  {
    id: 'l7',
    name: 'Erciyes',
    tier: 'silver',
    logoUrl: '/Erciyes.png'
  },
  {
    id: 'l8',
    name: 'ISG',
    tier: 'silver',
    logoUrl: '/ISG.png'
  },
  {
    id: 'l9',
    name: 'Medicasimple',
    tier: 'gold',
    logoUrl: '/Medicasimple.png'
  },
  {
    id: 'l10',
    name: 'Proant',
    tier: 'gold',
    logoUrl: '/Proant.jpg'
  }
];

// Sağ taraf sponsorları (8 adet)
export const RIGHT_SPONSORS: Sponsor[] = [
  {
    id: 'r1',
    name: 'KDD',
    tier: 'gold',
    logoUrl: '/KDD.png'
  },
  {
    id: 'r2',
    name: 'HO',
    tier: 'silver',
    logoUrl: '/HO.png'
  },
  {
    id: 'r3',
    name: 'Okyanus Dental',
    tier: 'gold',
    logoUrl: '/OkyanusDentalLogo.png'
  },
  {
    id: 'r4',
    name: 'SAM',
    tier: 'gold',
    logoUrl: '/SAM.png'
  },
  {
    id: 'r5',
    name: 'SDD',
    tier: 'gold',
    logoUrl: '/SDD.png'
  },
  {
    id: 'r6',
    name: 'Seçil Bayrak',
    tier: 'silver',
    logoUrl: '/Seçil Bayrak.png'
  },
  {
    id: 'r7',
    name: 'TÖMER',
    tier: 'silver',
    logoUrl: '/TÖMER.png'
  },
  {
    id: 'r8',
    name: 'Zemzem',
    tier: 'silver',
    logoUrl: '/Zemzem.png'
  },
  {
    id: 'r9',
    name: 'Intime',
    tier: 'gold',
    logoUrl: '/Intime.png'
  }
];

// Eski sponsor listeleri (uyumluluk için)
export const GOLD_SPONSORS = LEFT_SPONSORS;
export const SILVER_BRONZE_SPONSORS = RIGHT_SPONSORS;

export const INITIAL_PARTICIPANTS: Participant[] = [
  { id: 'p1', fullName: 'HÜSNİYE KARAMIK' },
  { id: 'p2', fullName: 'VİLDAN TOPCU' },
  { id: 'p3', fullName: 'ARİF SERMED ERDEM' },
  { id: 'p4', fullName: 'DOĞAN AKDENİZ' },
  { id: 'p5', fullName: 'MEHMET SEZER' },
  { id: 'p6', fullName: 'ARİFE GÜL AKÇAAĞAÇ' },
  { id: 'p7', fullName: 'FATMANA OĞUZ' },
  { id: 'p8', fullName: 'MİHRİBAN GÜNGÖRÜ' },
  { id: 'p9', fullName: 'AYSUN DÖNER' },
  { id: 'p10', fullName: 'KÜBRA SIRIK' },
  { id: 'p11', fullName: 'ŞEVKET TAİROĞLU' },
  { id: 'p12', fullName: 'HAKAN TÜRK' },
  { id: 'p13', fullName: 'FATMA NUR YILMAZ' },
  { id: 'p14', fullName: 'TUFAN ERKAYA' },
  { id: 'p15', fullName: 'HATİCE NUR ÜLKER' },
  { id: 'p16', fullName: 'EREN AYDIN' },
  { id: 'p17', fullName: 'ALİHAN ŞAHBAZ' },
  { id: 'p18', fullName: 'SONER AZBOZ' },
  { id: 'p19', fullName: 'HAMİD TAİROĞLU' },
  { id: 'p20', fullName: 'EFE KARAOSMANOĞLU' },
  { id: 'p21', fullName: 'EYÜP CİHAN' },
  { id: 'p22', fullName: 'ALİZAR NUFAROĞLU' },
  { id: 'p23', fullName: 'YASİN MEDET' },
  { id: 'p24', fullName: 'EMİNE GÜNGÖRDÜ' },
  { id: 'p25', fullName: 'SABRİYE KULA' },
  { id: 'p26', fullName: 'KADİR İSMAİLOĞLU' },
  { id: 'p27', fullName: 'EMRE ARICAN' },
  { id: 'p28', fullName: 'ZEHRA SARIKAYA' },
  { id: 'p29', fullName: 'İPEK CAN' },
  { id: 'p30', fullName: 'FİRUZE AKTÜRK' },
  { id: 'p31', fullName: 'ÖMER SARIKAYA' },
  { id: 'p32', fullName: 'MEDİNA YENİAY' },
  { id: 'p33', fullName: 'RIDVAN ATEŞ' },
  { id: 'p34', fullName: 'TUĞBA ÇAKIRER' },
  { id: 'p35', fullName: 'ELİF DOĞAN' },
  { id: 'p36', fullName: 'AHMET GÜLTEKİN' },
  { id: 'p37', fullName: 'DOĞUKAN MUTLU' },
  { id: 'p38', fullName: 'REVNAK AKBURAK' },
  { id: 'p39', fullName: 'KADİR KAAN KÖKLÜ' },
  { id: 'p40', fullName: 'FATMA İNCE' },
  { id: 'p41', fullName: 'MELEK KAYMAK' },
  { id: 'p42', fullName: 'HÜMEYRA AKYALÇIN' },
  { id: 'p43', fullName: 'MİHRİBAN GÜRCAN' },
  { id: 'p44', fullName: 'FATMA GÜNER' },
  { id: 'p45', fullName: 'HAKAN GÜLER' },
  { id: 'p46', fullName: 'HATİCE GÜLER' },
  { id: 'p47', fullName: 'ALEYNA HELİN SARI' },
  { id: 'p48', fullName: 'TUĞÇE ÇAKIR' },
  { id: 'p49', fullName: 'GÜLSÜM ATEŞ' },
  { id: 'p50', fullName: 'NAZİRE ERTEKİN' },
  { id: 'p51', fullName: 'AHMET ALKAN' },
  { id: 'p52', fullName: 'GÜVENÇ KİZİROĞLU' },
  { id: 'p53', fullName: 'BERRİN KOÇ' },
  { id: 'p54', fullName: 'İLAYDA CULUK' },
  { id: 'p55', fullName: 'İLAYDA TAŞLAROĞLU' },
  { id: 'p56', fullName: 'CEREN KUŞ' },
  { id: 'p57', fullName: 'ZEYNEP AKSÖZ' },
  { id: 'p58', fullName: 'MURAT YILMAZ' },
  { id: 'p59', fullName: 'CEYDA ÇETİN' },
  { id: 'p60', fullName: 'DENİZ DURMAZ' },
  { id: 'p61', fullName: 'BETÜL GENCER' },
  { id: 'p62', fullName: 'ÖZGE AYKIN' },
  { id: 'p63', fullName: 'EMRE ACAR' },
  { id: 'p64', fullName: 'SEVDA ÇAVUŞOĞLU' },
  { id: 'p65', fullName: 'BUSE AŞKIN' },
  { id: 'p66', fullName: 'CEMİL İSMAİLOĞLU' },
  { id: 'p67', fullName: 'HATİCE KÖREGEN' },
  { id: 'p68', fullName: 'MELİH ÇOBAN' },
  { id: 'p69', fullName: 'OYA ALTUNKAYNAK' },
  { id: 'p70', fullName: 'ALPARSLAN LÜTFÜ YAMUK' },
  { id: 'p71', fullName: 'RÜSTEM AZAK' },
  { id: 'p72', fullName: 'HARUN GÖKÇE' },
  { id: 'p73', fullName: 'EMİNE ÇAKAN' },
  { id: 'p74', fullName: 'EMRE AYIN' },
  { id: 'p75', fullName: 'NURAY KARAOSMANOĞLU' },
  { id: 'p76', fullName: 'HAYRİYE ALKAN' },
  { id: 'p77', fullName: 'BAYRAM BEKİR' },
  { id: 'p78', fullName: 'METE GÜNEŞ' },
  { id: 'p79', fullName: 'DİLEK ACAR' },
  { id: 'p80', fullName: 'HAYRİYE KESKİN' },
  { id: 'p81', fullName: 'FURKAN YILMAZ' },
  { id: 'p82', fullName: 'GAMZE ÜSTÜNDAĞ' },
  { id: 'p83', fullName: 'ÜMMÜ GÜLSÜM ÖZGÜL' },
  { id: 'p84', fullName: 'AHMET KARAMANOĞLU' },
  { id: 'p85', fullName: 'AYŞEGÜL FİDAN' },
  { id: 'p86', fullName: 'NURCAN BERK' },
  { id: 'p87', fullName: 'İREM ŞAHİN' },
  { id: 'p88', fullName: 'EMİN ABDULLAH' },
  { id: 'p89', fullName: 'SERDAR SÜDAŞ' },
  { id: 'p90', fullName: 'DUDU ÖNGEN' },
  { id: 'p91', fullName: 'UFUK AKPINAR' },
  { id: 'p92', fullName: 'ASLI SAFİNUR YAMA' },
  { id: 'p93', fullName: 'ALİ CİHAN' },
  { id: 'p94', fullName: 'EMİNE DURMAZ' },
  { id: 'p95', fullName: 'AYŞE KÜBRA KARAKAYA' },
  { id: 'p96', fullName: 'SUPHİ KARA' },
  { id: 'p97', fullName: 'YUDUM ÖZKUL' },
  { id: 'p98', fullName: 'ÇAĞLAR BAYRAM' },
  { id: 'p99', fullName: 'HAZAL DUYULER' },
  { id: 'p100', fullName: 'SEMRA DENİZ' },
  { id: 'p101', fullName: 'HASAN ÖZTAŞ' },
  { id: 'p102', fullName: 'TUBA ÖKSÜZOĞLU' },
  { id: 'p103', fullName: 'HACER DAYANGAN' },
  { id: 'p104', fullName: 'HAFİZE YENİALTUN' },
  { id: 'p105', fullName: 'CELİL SULIYEV' },
  { id: 'p106', fullName: 'CEHYUN BİRİNCİ' },
  { id: 'p107', fullName: 'NURHAN BİÇİCİ' },
  { id: 'p108', fullName: 'ASLI ATASEVEN' },
  { id: 'p109', fullName: 'MERVE TERAT' },
  { id: 'p110', fullName: 'CEM EREN DEMİR' },
  { id: 'p111', fullName: 'EMİNE GÖKKUŞ' },
  { id: 'p112', fullName: 'LEYLA GÜNERKAYA' },
  { id: 'p113', fullName: 'EZEL KAYA' },
  { id: 'p114', fullName: 'ZEHRA BİNNUR USLUCAN' },
  { id: 'p115', fullName: 'RIZA OSMANLI' },
  { id: 'p116', fullName: 'ABBAS AHMET' },
  { id: 'p117', fullName: 'ANSAR İSMAİL' },
  { id: 'p118', fullName: 'TURGAY KILIÇ' },
  { id: 'p119', fullName: 'GÖRKEM IŞIK' },
  { id: 'p120', fullName: 'EZGİ BİNGÖL' },
  { id: 'p121', fullName: 'MERYEM GÜREKKAYA' },
  { id: 'p122', fullName: 'SEMİH ÖZER' },
  { id: 'p123', fullName: 'OĞUZHAN ASLAN' },
  { id: 'p124', fullName: 'EMİRCAN BİRKAN' },
  { id: 'p125', fullName: 'LAÇİN BAHRİ' },
  { id: 'p126', fullName: 'İSMAİL ÖZKAN' },
  { id: 'p127', fullName: 'HÜSEYİN ARSLAN' },
  { id: 'p128', fullName: 'EMİRHAN KÖREGEN' },
  { id: 'p129', fullName: 'OĞUZHAN ŞAHİNER' },
  { id: 'p130', fullName: 'TAYFUN UMUT ARDIÇ' },
  { id: 'p131', fullName: 'GAYE YÜCEL' },
  { id: 'p132', fullName: 'BUKET EFE' },
  { id: 'p133', fullName: 'FATMA TUNCA' },
  { id: 'p134', fullName: 'AHMET UMUT AYRALER' },
  { id: 'p135', fullName: 'VIKTORIIA MALISHEVSKA' },
  { id: 'p136', fullName: 'MEDİNE ŞAHBAZ' },
  { id: 'p137', fullName: 'HİDAYET EMRAH UĞUR' },
  { id: 'p138', fullName: 'ALİ EŞREF ARSEVEN' },
  { id: 'p139', fullName: 'EMİR SALİMOĞLU' },
  { id: 'p140', fullName: 'ARDA SÖNMEZ' },
  { id: 'p141', fullName: 'MAURIZIO LORENZON' },
  { id: 'p142', fullName: 'ENES MÜCAHİT' },
  { id: 'p143', fullName: 'MEHMET KOCABAŞ' },
  { id: 'p144', fullName: 'KEZİBAN PESEN' },
  { id: 'p145', fullName: 'BUSE NAZ TEKE' },
  { id: 'p146', fullName: 'FATMA GÖRGEL' },
  { id: 'p147', fullName: 'AŞKIN GÜNGÖREN' },
  { id: 'p148', fullName: 'MERT KARACA' },
  { id: 'p149', fullName: 'İRDE BAŞAK' },
  { id: 'p150', fullName: 'MUHAMMET İSMAİLOĞLU' },
  { id: 'p151', fullName: 'FATMA KARACA' },
  { id: 'p152', fullName: 'BARAN MAYANCUR' },
  { id: 'p153', fullName: 'GECE YEŞİLYURT' },
  { id: 'p154', fullName: 'OKAN İNCEDAYI' },
  { id: 'p155', fullName: 'ARAS ŞANIVAR' },
  { id: 'p156', fullName: 'EMRAL UĞUR' },
];

export const RAFFLE_RESULTS: RaffleResult[] = [
  { id: 'r1', winnerName: '', giftTitle: '%50 İNDİRİMLİ 1 KUR İNGİLİZCE DİL EĞİTİMİ', giftCategory: 'Eğitim', sponsor: 'English Journey', drawnAt: '' },
  { id: 'r2', winnerName: '', giftTitle: '1 KUR DİL EĞİTİMİ', giftCategory: 'Eğitim', sponsor: 'TÖMER', drawnAt: '' },
  { id: 'r3', winnerName: '', giftTitle: '1 KUR İNGİLİZCE DİL EĞİTİMİ', giftCategory: 'Eğitim', sponsor: 'English Journey', drawnAt: '' },
  { id: 'r4', winnerName: '', giftTitle: '1.000TL AKARYAKIT KARTI', giftCategory: 'Hediye Kartı', sponsor: 'OPET HESAPÇIOĞLU', drawnAt: '' },
  { id: 'r5', winnerName: '', giftTitle: '1.000TL AKARYAKIT KARTI', giftCategory: 'Hediye Kartı', sponsor: 'OPET HESAPÇIOĞLU', drawnAt: '' },
  { id: 'r6', winnerName: '', giftTitle: '10.000 TL', giftCategory: 'Nakit', sponsor: 'KIVANÇ DİŞ DEPOSU', drawnAt: '' },
  { id: 'r7', winnerName: '', giftTitle: '15.000 TL', giftCategory: 'Nakit', sponsor: 'ANİSA DENTAL', drawnAt: '' },
  { id: 'r8', winnerName: '', giftTitle: '15.000 TL', giftCategory: 'Nakit', sponsor: 'SİDE DİŞ DEPOSU', drawnAt: '' },
  { id: 'r9', winnerName: '', giftTitle: '5000 TL MULTIGIFT', giftCategory: 'Hediye Kartı', sponsor: 'INTIME', drawnAt: '' },
  { id: 'r10', winnerName: '', giftTitle: '5000 TL MULTIGIFT', giftCategory: 'Hediye Kartı', sponsor: 'INTIME', drawnAt: '' },
  { id: 'r11', winnerName: '', giftTitle: 'AĞIZ DUŞU SETİ', giftCategory: 'Sağlık', sponsor: 'AMAZON DENTAL', drawnAt: '' },
  { id: 'r12', winnerName: '', giftTitle: 'AĞIZ DUŞU SETİ', giftCategory: 'Sağlık', sponsor: 'AMAZON DENTAL', drawnAt: '' },
  { id: 'r13', winnerName: '', giftTitle: 'AİRPODS 4', giftCategory: 'Teknoloji', sponsor: 'MUSTAFA BEY İSG UZMANI', drawnAt: '' },
  { id: 'r14', winnerName: '', giftTitle: 'BLENDER', giftCategory: 'Ev Aletleri', sponsor: 'ACURATA FREZ', drawnAt: '' },
  { id: 'r15', winnerName: '', giftTitle: 'ÇEYREK ALTIN', giftCategory: 'Altın', sponsor: 'ERCİYES MATBAA', drawnAt: '' },
  { id: 'r16', winnerName: '', giftTitle: 'ÇEYREK ALTIN', giftCategory: 'Altın', sponsor: 'ETDA KİMYA BETÜL HANIM', drawnAt: '' },
  { id: 'r17', winnerName: '', giftTitle: 'ÇEYREK ALTIN', giftCategory: 'Altın', sponsor: 'MEHMET VE ŞENİZ DEMİRKALEM DMK TURİZM', drawnAt: '' },
  { id: 'r18', winnerName: '', giftTitle: 'ÇEYREK ALTIN', giftCategory: 'Altın', sponsor: 'MEHMET VE ŞENİZ DEMİRKALEM DMK TURİZM', drawnAt: '' },
  { id: 'r19', winnerName: '', giftTitle: 'ÇEYREK ALTIN', giftCategory: 'Altın', sponsor: 'MEHMET VE ŞENİZ DEMİRKALEM DMK TURİZM', drawnAt: '' },
  { id: 'r20', winnerName: '', giftTitle: 'ÇEYREK ALTIN', giftCategory: 'Altın', sponsor: 'CORE DENT', drawnAt: '' },
  { id: 'r21', winnerName: '', giftTitle: 'ÇEYREK ALTIN', giftCategory: 'Altın', sponsor: 'CORE DENT', drawnAt: '' },
  { id: 'r22', winnerName: '', giftTitle: 'ÇEYREK ALTIN', giftCategory: 'Altın', sponsor: 'CAM LOOK', drawnAt: '' },
  { id: 'r23', winnerName: '', giftTitle: 'ÇEYREK ALTIN', giftCategory: 'Altın', sponsor: 'CAM LOOK', drawnAt: '' },
  { id: 'r24', winnerName: '', giftTitle: 'ÇEYREK ALTIN', giftCategory: 'Altın', sponsor: 'BORA DENTAL', drawnAt: '' },
  { id: 'r25', winnerName: '', giftTitle: 'ÇEYREK ALTIN', giftCategory: 'Altın', sponsor: 'BORA DENTAL', drawnAt: '' },
  { id: 'r26', winnerName: '', giftTitle: 'ÇEYREK ALTIN', giftCategory: 'Altın', sponsor: 'BORA DENTAL', drawnAt: '' },
  { id: 'r27', winnerName: '', giftTitle: 'ÇEYREK ALTIN', giftCategory: 'Altın', sponsor: 'ZEMZEM TURİZM', drawnAt: '' },
  { id: 'r28', winnerName: '', giftTitle: 'ÇEYREK ALTIN', giftCategory: 'Altın', sponsor: 'ZEMZEM TURİZM', drawnAt: '' },
  { id: 'r29', winnerName: '', giftTitle: 'ÇEYREK ALTIN', giftCategory: 'Altın', sponsor: 'ZEMZEM TURİZM', drawnAt: '' },
  { id: 'r30', winnerName: '', giftTitle: 'ÇEYREK ALTIN', giftCategory: 'Altın', sponsor: 'ZEMZEM TURİZM', drawnAt: '' },
  { id: 'r31', winnerName: '', giftTitle: 'ÇEYREK ALTIN', giftCategory: 'Altın', sponsor: 'ZEMZEM TURİZM', drawnAt: '' },
  { id: 'r32', winnerName: '', giftTitle: 'ÇEYREK ALTIN', giftCategory: 'Altın', sponsor: 'ZEMZEM TURİZM', drawnAt: '' },
  { id: 'r33', winnerName: '', giftTitle: 'İLERİ SEVİYE EXCEL KURSU', giftCategory: 'Eğitim', sponsor: 'TÖMER', drawnAt: '' },
  { id: 'r34', winnerName: '', giftTitle: 'JBL FLIP 7 SES BOMBASI', giftCategory: 'Teknoloji', sponsor: 'PROANT', drawnAt: '' },
  { id: 'r35', winnerName: '', giftTitle: 'TÜRK KAHVESİ MAKİNASI', giftCategory: 'Ev Aletleri', sponsor: 'SEÇİL BAYRAK PROMOSYON FİRMASI', drawnAt: '' },
  { id: 'r36', winnerName: '', giftTitle: 'TÜRK KAHVESİ MAKİNASI', giftCategory: 'Ev Aletleri', sponsor: 'AMAZON DENTAL', drawnAt: '' },
  { id: 'r37', winnerName: '', giftTitle: 'TÜRK KAHVESİ MAKİNASI', giftCategory: 'Ev Aletleri', sponsor: 'AMAZON DENTAL', drawnAt: '' },
  { id: 'r38', winnerName: '', giftTitle: 'XIAOMI BLUETOOTH HOPARLÖR', giftCategory: 'Teknoloji', sponsor: 'MEDICASIMPLE', drawnAt: '' },
];